/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn1/NGAP_Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -D ngap`
 */

#ifndef	_Ngap_EventType_H_
#define	_Ngap_EventType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_EventType {
	Ngap_EventType_direct	= 0,
	Ngap_EventType_change_of_serve_cell	= 1,
	Ngap_EventType_ue_presence_in_area_of_interest	= 2,
	Ngap_EventType_stop_change_of_serve_cell	= 3,
	Ngap_EventType_stop_ue_presence_in_area_of_interest	= 4,
	Ngap_EventType_cancel_location_reporting_for_the_ue	= 5
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_EventType;

/* Ngap_EventType */
typedef long	 Ngap_EventType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_EventType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_EventType;
extern const asn_INTEGER_specifics_t asn_SPC_EventType_specs_1;
asn_struct_free_f EventType_free;
asn_struct_print_f EventType_print;
asn_constr_check_f EventType_constraint;
per_type_decoder_f EventType_decode_aper;
per_type_encoder_f EventType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_EventType_H_ */
#include <asn_internal.h>
