/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn1/NGAP_Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -D ngap`
 */

#ifndef	_Ngap_TNLAssociationUsage_H_
#define	_Ngap_TNLAssociationUsage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_TNLAssociationUsage {
	Ngap_TNLAssociationUsage_ue	= 0,
	Ngap_TNLAssociationUsage_non_ue	= 1,
	Ngap_TNLAssociationUsage_both	= 2
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_TNLAssociationUsage;

/* Ngap_TNLAssociationUsage */
typedef long	 Ngap_TNLAssociationUsage_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_TNLAssociationUsage_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_TNLAssociationUsage;
extern const asn_INTEGER_specifics_t asn_SPC_TNLAssociationUsage_specs_1;
asn_struct_free_f TNLAssociationUsage_free;
asn_struct_print_f TNLAssociationUsage_print;
asn_constr_check_f TNLAssociationUsage_constraint;
per_type_decoder_f TNLAssociationUsage_decode_aper;
per_type_encoder_f TNLAssociationUsage_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_TNLAssociationUsage_H_ */
#include <asn_internal.h>
